<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        $patientTypeId = DB::table('user_types')
            ->where('nombre', 'Paciente')
            ->value('id_tipo_usuario');

        if (!$patientTypeId) {
            throw new \RuntimeException('Tipo de usuario "Paciente" no encontrado. Ejecuta UserTypeSeeder primero.');
        }

        DB::table('users')->insert([
            [
                'id_usuario' => 2,
                'id_tipo_usuario' => 1,
                'id_tipo_documento' => 1,
                'numero_documento' => '123456789',
                'correo_electronico' => 'admin@ips.com',
                'telefono' => null,
                'estado' => 'activo',
                'nombres' => 'Juan',
                'apellidos' => 'Admin',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => null,
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 02:02:39',
                'updated_at' => '2025-11-01 02:02:39',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 3,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '987654321',
                'correo_electronico' => 'carlos@empresa.com',
                'telefono' => '3124567890',
                'estado' => 'activo',
                'nombres' => 'Carlos',
                'apellidos' => 'Gómez',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-10-31',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 02:52:24',
                'updated_at' => '2025-11-01 02:52:24',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 6,
                'id_tipo_usuario' => 1,
                'id_tipo_documento' => 1,
                'numero_documento' => '122445566',
                'correo_electronico' => 'admn@ips.com',
                'telefono' => null,
                'estado' => 'activo',
                'nombres' => 'Juan',
                'apellidos' => 'Admn',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => null,
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 03:48:18',
                'updated_at' => '2025-11-01 03:48:18',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 7,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '987654221',
                'correo_electronico' => 'carl@empresa.com',
                'telefono' => '3124563890',
                'estado' => 'activo',
                'nombres' => 'Carlos',
                'apellidos' => 'Gmez',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-01',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 22:41:41',
                'updated_at' => '2025-11-01 22:41:41',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 8,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '987654251',
                'correo_electronico' => 'carl@emresa.com',
                'telefono' => '3124563898',
                'estado' => 'activo',
                'nombres' => 'Carlo',
                'apellidos' => 'Gmz',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-01',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 22:57:29',
                'updated_at' => '2025-11-01 22:57:29',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 9,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '987654254',
                'correo_electronico' => 'carl@emrea.com',
                'telefono' => '3124563898',
                'estado' => 'activo',
                'nombres' => 'Carlo',
                'apellidos' => 'Gmz',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-01',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 22:58:57',
                'updated_at' => '2025-11-01 22:58:57',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 11,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '1097491938',
                'correo_electronico' => 'jescobar@ips.com',
                'telefono' => '3203922383',
                'estado' => 'activo',
                'nombres' => 'Juan Guillermo',
                'apellidos' => 'Escobar Baez',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-01',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-01 23:55:50',
                'updated_at' => '2025-11-01 23:55:50',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 12,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '10974899',
                'correo_electronico' => 'juanguieoar05@mail.com',
                'telefono' => '3203923394',
                'estado' => 'activo',
                'nombres' => 'Juan Guillerm',
                'apellidos' => 'Escobar Bae',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-02',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-02 08:10:34',
                'updated_at' => '2025-11-02 08:10:34',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 13,
                'id_tipo_usuario' => 1,
                'id_tipo_documento' => 2,
                'numero_documento' => '8888888888',
                'correo_electronico' => 'sergio@ips.com',
                'telefono' => '4444444444',
                'estado' => 'activo',
                'nombres' => 'Sergio',
                'apellidos' => 'Escobar Gomez',
                'fecha_nacimiento' => '2000-06-02',
                'fecha_ingreso_ips' => '2025-10-30',
                'fecha_creacion_sistema' => '2025-11-02',
                'observaciones' => 'Es nuevo en la empresa',
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-03 02:23:27',
                'updated_at' => '2025-11-03 02:23:27',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 14,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 4,
                'numero_documento' => '100000000',
                'correo_electronico' => 'jjjj@gmail.com',
                'telefono' => '3303922383',
                'estado' => 'activo',
                'nombres' => 'Juan',
                'apellidos' => 'Escobar B',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-02',
                'observaciones' => 'Es de prueba',
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-03 02:47:09',
                'updated_at' => '2025-11-03 02:47:09',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 15,
                'id_tipo_usuario' => 1,
                'id_tipo_documento' => 1,
                'numero_documento' => '1000000000',
                'correo_electronico' => 'admin@test.com',
                'telefono' => '3001234567',
                'estado' => 'activo',
                'nombres' => 'Usuario',
                'apellidos' => 'Administrador',
                'fecha_nacimiento' => '1990-01-01',
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => null,
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-03 05:36:56',
                'updated_at' => '2025-11-04 20:37:47',
                'ultimo_acceso' => '2025-11-04 20:37:47',
            ],
            [
                'id_usuario' => 16,
                'id_tipo_usuario' => 2,
                'id_tipo_documento' => 1,
                'numero_documento' => '200000000',
                'correo_electronico' => 'descobar@unab.com',
                'telefono' => null,
                'estado' => 'activo',
                'nombres' => 'David',
                'apellidos' => 'Baez',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-03',
                'observaciones' => 'Creado con autenticación',
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-04 02:30:58',
                'updated_at' => '2025-11-04 02:30:58',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 18,
                'id_tipo_usuario' => $patientTypeId,
                'id_tipo_documento' => 1,
                'numero_documento' => '40000000',
                'correo_electronico' => 'juliana@ips.com',
                'telefono' => '33333333',
                'estado' => 'activo',
                'nombres' => 'Juliana',
                'apellidos' => 'Escobar',
                'fecha_nacimiento' => null,
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => '2025-11-04',
                'observaciones' => null,
                'password' => bcrypt('12345678'),
                'created_at' => '2025-11-04 16:08:48',
                'updated_at' => '2025-11-04 16:08:48',
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 19,
                'id_tipo_usuario' => $patientTypeId,
                'id_tipo_documento' => 1,
                'numero_documento' => '40000001',
                'correo_electronico' => 'lina.paciente@ips.com',
                'telefono' => '3201112233',
                'estado' => 'activo',
                'nombres' => 'Lina',
                'apellidos' => 'Morales',
                'fecha_nacimiento' => '1989-03-15',
                'fecha_ingreso_ips' => null,
                'fecha_creacion_sistema' => null,
                'observaciones' => 'Paciente con seguimiento trimestral.',
                'password' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'ultimo_acceso' => null,
            ],
            [
                'id_usuario' => 20,
                'id_tipo_usuario' => $patientTypeId,
                'id_tipo_documento' => 2,
                'numero_documento' => '50000002',
                'correo_electronico' => 'diego.paciente@ips.com',
                'telefono' => '3015556677',
                'estado' => 'activo',
                'nombres' => 'Diego',
                'apellidos' => 'Ramírez',
                'fecha_nacimiento' => '1992-11-02',
                'fecha_ingreso_ips' => '2023-05-10',
                'fecha_creacion_sistema' => null,
                'observaciones' => 'Control de hipertensión.',
                'password' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'ultimo_acceso' => null,
            ],


            [
            'id_usuario' => 21,
            'id_tipo_usuario' => 3, // Secretaria
            'id_tipo_documento' => 1,
            'numero_documento' => '60000001',
            'correo_electronico' => 'maria.secretaria@ips.com',
            'telefono' => '3105559988',
            'estado' => 'activo',
            'nombres' => 'María',
            'apellidos' => 'López Gómez',
            'fecha_nacimiento' => '1995-07-12',
            'fecha_ingreso_ips' => '2024-01-15',
            'fecha_creacion_sistema' => now(),
            'observaciones' => 'Secretaria de recepción principal',
            'password' => bcrypt('12345678'),
            'created_at' => now(),
            'updated_at' => now(),
            'ultimo_acceso' => null,
        ],
        [
            'id_usuario' => 22,
            'id_tipo_usuario' => 3, // Secretaria
            'id_tipo_documento' => 1,
            'numero_documento' => '60000002',
            'correo_electronico' => 'laura.secretaria@ips.com',
            'telefono' => '3204446677',
            'estado' => 'activo',
            'nombres' => 'Laura',
            'apellidos' => 'Martínez Rojas',
            'fecha_nacimiento' => '1993-04-05',
            'fecha_ingreso_ips' => '2024-03-01',
            'fecha_creacion_sistema' => now(),
            'observaciones' => 'Secretaria del área de consultas externas',
            'password' => bcrypt('12345678'),
            'created_at' => now(),
            'updated_at' => now(),
            'ultimo_acceso' => null,
        ],

        ]);
    }
}
